site_name: Godot Oculus Platform
site_url: https://decacis.github.io/godot_oculus_platform
site_description: An implementation of the Oculus Platform SDK for the Godot Engine.
repo_url: https://github.com/decacis/godot_oculus_platform
edit_uri: https://github.com/decacis/godot_oculus_platform/tree/gh-pages-source/docs
nav:
  - Home: index.md
  - Getting started: getting-started.md
  - Examples: examples.md
  - Build: build.md
  - Functions:
    - Initialization: 'functions/initialization.md'
    - Users: 'functions/users.md'
theme:
  name: material
  logo: assets/gdop_logo_w.svg
  favicon: assets/gdop_256.png
  palette:
    - scheme: default
      primary: blue grey
      accent: blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - content.code.annotate
markdown_extensions:
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.blocks.admonition
  - pymdownx.blocks.details